### ISSUE TITLE
Разобраться с картинками

### ISSUE THREAD

**Issue by polynx** [grdt/foxlot#1]
1) Где менять ту, что на главной? (не нашли)
2) Как задать картинку блогу (сейчас она исчезла)
3) Как сделать, чтобы при переходе в запись общая картинка блога оставалась, а не менялась на дубль миниатюры записи

**Comment by pasynkov** [comment]
1) меняется миниатюрой страницы "Главная", либо берется картинка блога
2) Внешний вид -> темы -> настроить -> изображение заголовка
3) добавляем метку "стандартная картинка", она не будет показываться в общем списке, но картинка установится блоговой
