### ISSUE TITLE
Перенести сайдбар

### ISSUE THREAD

**Issue by polynx** [grdt/foxlot#10]
Общий сайдбар (правый) блога - чтобы отображался и на внутренних страничках блога

**Comment by pasynkov** [comment]
готово

**Comment by polynx** [comment]
Внутренняя страница выглядит странно: http://foxlot.ru/2015/07/13/%D1%87%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-%D0%B6%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5-%D1%84%D1%8D%D0%BD%D1%82%D0%B5%D0%B7%D0%B8/
