### ISSUE TITLE
Картинки (!) не одна из рекомендаций не сработала

### ISSUE THREAD

**Issue by polynx** [grdt/foxlot#11]
1) меняется миниатюрой страницы "Главная", либо берется картинка блога - сделала, нет изменений
2) Внешний вид -> темы -> настроить -> изображение заголовка - сделала, нет изменений
3) добавляем метку "стандартная картинка", она не будет показываться в общем списке, но картинка установится блоговой - не нашла метки

**Comment by pasynkov** [comment]
1) починил
2) +
3) http://joxi.ru/v29yR1ZI4PkG2G
