### ISSUE TITLE
Прикрепить метки записи к тэгам

### ISSUE THREAD

**Issue by polynx** [grdt/foxlot#2]
Чтобы вот эти метки: http://joxi.ru/l2ZYjqEclnJzmJ
были синхронизированы с вот этими http://joxi.ru/brRnNxGUBbXOr1

**Comment by pasynkov** [comment]
готово

**Comment by polynx** [comment]
там есть какое-то ограничение по количеству? мне бы не хотелось простыню тегов сбоку

**Comment by pasynkov** [comment]
нету, простыня тэгов - это нормально. будет проблема - будем решать
