### ISSUE TITLE
Категории

### ISSUE THREAD

**Issue by polynx** [grdt/foxlot#5]
Подцепить реально созданные категории блога к http://joxi.ru/4AkE16aTj43lmq

**Comment by pasynkov** [comment]
готово

**Comment by polynx** [comment]
При клике на Категорию какая-то страшная ебола: http://foxlot.ru/category/%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8/

аналогично при клике на тэг: http://foxlot.ru/tag/%D0%B6%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5-%D1%84%D1%8D%D0%BD%D1%82%D0%B5%D0%B7%D0%B8/

**Comment by pasynkov** [comment]
+
